DROP TABLE IF EXISTS healthcare_catalog_db.raw_nh_providerinfo_oct2024_fixed;

CREATE EXTERNAL TABLE healthcare_catalog_db.raw_nh_providerinfo_oct2024_fixed (
  ccn_provnum                                                      string,
  provider_name                                                    string,
  provider_address                                                 string,
  provider_city                                                    string,
  provider_state                                                   string,
  provider_zip_code                                                string,
  telephone_number                                                 string,
  provider_ssa_county_code                                         string,
  county_parish                                                    string,
  ownership_type                                                   string,
  number_of_certified_beds                                         string,
  avg_residents_per_day                                            string,
  avg_residents_per_day_footnote                                   string,
  provider_type                                                    string,
  provider_resides_in_hospital                                     string,
  legal_business_name                                              string,
  date_first_approved_medicare_medicaid                            string,
  affiliated_entity_name                                           string,
  affiliated_entity_id                                             string,
  continuing_care_retirement_community                             string,
  special_focus_status                                             string,
  abuse_icon                                                       string,
  most_recent_health_inspection_more_than_2_years_ago              string,
  provider_changed_ownership_in_last_12_months                     string,
  with_a_resident_and_family_council                               string,
  automatic_sprinkler_systems_in_all_required_areas                string,
  overall_rating                                                   string,
  overall_rating_footnote                                          string,
  health_inspection_rating                                         string,
  health_inspection_rating_footnote                                string,
  qm_rating                                                        string,
  qm_rating_footnote                                               string,
  long_stay_qm_rating                                              string,
  long_stay_qm_rating_footnote                                     string,
  short_stay_qm_rating                                             string,
  short_stay_qm_rating_footnote                                    string,
  staffing_rating                                                  string,
  staffing_rating_footnote                                         string,
  reported_staffing_footnote                                       string,
  physical_therapist_staffing_footnote                             string,
  reported_nurse_aide_staffing_hours_per_resident_per_day          string,
  reported_lpn_staffing_hours_per_resident_per_day                 string,
  reported_rn_staffing_hours_per_resident_per_day                  string,
  reported_licensed_staffing_hours_per_resident_per_day            string,
  reported_total_nurse_staffing_hours_per_resident_per_day         string,
  weekend_total_nurse_staffing_hours_per_resident_per_day          string,
  weekend_rn_staffing_hours_per_resident_per_day                   string,
  reported_physical_therapist_staffing_hours_per_resident_per_day  string,
  total_nursing_staff_turnover                                     string,
  total_nursing_staff_turnover_footnote                            string,
  registered_nurse_turnover                                        string,
  registered_nurse_turnover_footnote                               string,
  number_of_administrators_who_have_left                           string,
  administrator_turnover_footnote                                  string,
  nursing_case_mix_index                                           string,
  nursing_case_mix_index_ratio                                     string,
  case_mix_nurse_aide_staffing_hours_per_resident_per_day          string,
  case_mix_lpn_staffing_hours_per_resident_per_day                 string,
  case_mix_rn_staffing_hours_per_resident_per_day                  string,
  case_mix_total_nurse_staffing_hours_per_resident_per_day         string,
  case_mix_weekend_total_nurse_staffing_hours_per_resident_per_day string,
  adjusted_nurse_aide_staffing_hours_per_resident_per_day          string,
  adjusted_lpn_staffing_hours_per_resident_per_day                 string,
  adjusted_rn_staffing_hours_per_resident_per_day                  string,
  adjusted_total_nurse_staffing_hours_per_resident_per_day         string,
  adjusted_weekend_total_nurse_staffing_hours_per_resident_per_day string,
  rating_cycle_1_standard_survey_health_date                       string,
  rating_cycle_1_total_number_of_health_deficiencies               string,
  rating_cycle_1_number_of_standard_health_deficiencies            string,
  rating_cycle_1_number_of_complaint_health_deficiencies           string,
  rating_cycle_1_health_deficiency_score                           string,
  rating_cycle_1_number_of_health_revisits                         string,
  rating_cycle_1_health_revisit_score                              string,
  rating_cycle_1_total_health_score                                string,
  rating_cycle_2_standard_health_survey_date                       string,
  rating_cycle_2_total_number_of_health_deficiencies               string,
  rating_cycle_2_number_of_standard_health_deficiencies            string,
  rating_cycle_2_number_of_complaint_health_deficiencies           string,
  rating_cycle_2_health_deficiency_score                           string,
  rating_cycle_2_number_of_health_revisits                         string,
  rating_cycle_2_health_revisit_score                              string,
  rating_cycle_2_total_health_score                                string,
  rating_cycle_3_standard_health_survey_date                       string,
  rating_cycle_3_total_number_of_health_deficiencies               string,
  rating_cycle_3_number_of_standard_health_deficiencies            string,
  rating_cycle_3_number_of_complaint_health_deficiencies           string,
  rating_cycle_3_health_deficiency_score                           string,
  rating_cycle_3_number_of_health_revisits                         string,
  rating_cycle_3_health_revisit_score                              string,
  rating_cycle_3_total_health_score                                string,
  total_weighted_health_survey_score                               string,
  number_of_facility_reported_incidents                            string,
  number_of_substantiated_complaints                               string,
  number_of_citations_from_infection_control_inspections           string,
  number_of_fines                                                  string,
  total_amount_of_fines_in_dollars                                 string,
  number_of_payment_denials                                        string,
  total_number_of_penalties                                        string,
  location                                                         string,
  latitude                                                         string,
  longitude                                                        string,
  geocoding_footnote                                               string,
  processing_date                                                  string
)
PARTITIONED BY (ingest_dt string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar'     = '"',
  'escapeChar'    = '\\'
)
STORED AS TEXTFILE
LOCATION 's3://healthcare-data-lake-gj/raw/nh_providerinfo_oct2024/'
TBLPROPERTIES ('skip.header.line.count'='1');